#!/usr/bin/env python3
# Copyright (c) 2025 Advanced Micro Devices, Inc.
# SPDX-License-Identifier: MIT
"""
kernel_grader.py — Kernel-level grader for the RL kernel-optimization sandbox.

Scoring (AgentKernelArena):
  compiled  → +20 pts
  correct   → +100 pts
  speedup S → +S×100 pts   (S = baseline_time / optimized_time)

Usage:
  python3 kernel_grader.py [--output-dir PATH] [--task TASK_ID] [--json]

Expected output/ layout:
  output/
    <task_id>/
      solution.hip | solution.py | solution.cu   ← optimized kernel
      config.yaml                                 ← generated by pipeline (not agent)

The grader reads this config, locates baseline + solution files, and runs
Magpie compare to evaluate compilation, correctness, and performance.
"""

from __future__ import annotations

import argparse
import ast
import hashlib
import json
import os
import re
import shlex
import shutil
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from score import (
    KernelResult,
    parse_task_config,
    run_magpie_compare,
    parse_compare_result,
    PTS_COMPILED, PTS_CORRECT,
)

try:
    from cache_manager import isolated_grading_env, clear_pycache
except ImportError:
    from contextlib import contextmanager

    @contextmanager
    def isolated_grading_env(**kwargs):
        yield {}

    def clear_pycache(p):
        pass

try:
    from config_generator import validate_config, write_config
except ImportError:
    validate_config = None  # type: ignore[assignment]
    write_config = None  # type: ignore[assignment]

REPO_ROOT  = Path(__file__).parent.parent
OUTPUT_DIR = REPO_ROOT / "output"

SOLUTION_NAMES = ["solution.hip", "solution.py", "solution.cu", "kernel.hip", "kernel.py"]


def find_tasks(output_dir: Path) -> list[Path]:
    """Return task directories that contain a solution file."""
    tasks = []
    for d in sorted(output_dir.iterdir()):
        if not d.is_dir():
            continue
        if any((d / s).exists() for s in SOLUTION_NAMES):
            tasks.append(d)
    return tasks


def find_solution(task_dir: Path) -> Path | None:
    for name in SOLUTION_NAMES:
        p = task_dir / name
        if p.exists():
            return p
    return None


def _detect_benchmark_tampering(solution_path: Path, baseline_path: str) -> list[str]:
    """Detect solutions that tamper with the benchmark via __main__ fast-exit tricks.

    Only flags ``__main__`` blocks that contain genuinely suspicious patterns
    (SystemExit, hardcoded PASS, fabricated timings).  A ``__main__`` block
    that simply runs the kernel for testing is NOT flagged.

    Returns a list of warning strings.  An empty list means no tampering detected.
    """
    warnings: list[str] = []
    try:
        src = solution_path.read_text()
        tree = ast.parse(src)
    except Exception:
        return warnings

    for node in ast.walk(tree):
        if not isinstance(node, ast.If):
            continue
        test = node.test
        is_main_guard = False
        if isinstance(test, ast.Compare):
            left = test.left
            if isinstance(left, ast.Name) and left.id == "__name__":
                is_main_guard = True
            elif isinstance(left, ast.Constant) and left.value == "__main__":
                is_main_guard = True
        if not is_main_guard:
            continue

        body_src = ast.get_source_segment(src, node)
        if body_src is None:
            continue

        if "SystemExit" in body_src or "sys.exit" in body_src or "os._exit" in body_src:
            warnings.append(
                "Solution has SystemExit/sys.exit inside __main__ guard — "
                "likely tampering with standalone benchmark measurement"
            )
        if re.search(r'BENCHMARK_MS:\s*[\d.]+', body_src):
            warnings.append(
                "Solution prints hardcoded BENCHMARK_MS inside __main__ guard — "
                "fabricated benchmark number"
            )
        if re.search(r'print\s*\(\s*["\']PASS["\']\s*\)', body_src):
            warnings.append(
                "Solution prints hardcoded PASS inside __main__ guard — "
                "bypassing correctness check"
            )

    return warnings


def _parse_config(config_path: Path) -> dict:
    """Parse a task config.yaml and return the dict."""
    return parse_task_config(config_path)


def _detect_kernel_type(solution: Path) -> str:
    """Infer Magpie kernel type from the solution file extension and content.

    Uses "triton" for Python kernels so Magpie runs them as standalone scripts
    (checking exit code and PASS output) rather than requiring Model/get_inputs
    functions that the pytorch mode expects.
    """
    ext = solution.suffix.lower()
    if ext in (".hip", ".cu"):
        return "hip"
    return "triton"


def _run_benchmark_script(script_path: str, python_bin: str, cwd: str, timeout: int = 120) -> float:
    """Run a kernel script and measure its execution time.

    Tries multiple strategies:
    1. Run with --benchmark flag and parse BENCHMARK_MS from stdout
    2. If no BENCHMARK_MS, parse common patterns like 'avg: X.XXms' or 'X.XX ms/iter'
    3. Fall back to measuring wall-clock time of the script itself
    """
    # Strategy 1: Try --benchmark flag first
    cmd = [python_bin, script_path, "--benchmark"]
    try:
        proc = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout, cwd=cwd)
        if proc.returncode == 0:
            match = re.search(r"BENCHMARK_MS:\s*([\d.]+)", proc.stdout)
            if match:
                return float(match.group(1))
    except (subprocess.TimeoutExpired, Exception):
        pass

    # Strategy 2: Run without --benchmark and try parsing output for timing
    cmd = [python_bin, script_path]
    try:
        import time as _time
        t0 = _time.monotonic()
        proc = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout, cwd=cwd)
        wall_ms = (_time.monotonic() - t0) * 1000.0

        if proc.returncode != 0:
            return 0.0

        # Parse common patterns
        for pattern in [
            r"BENCHMARK_MS:\s*([\d.]+)",
            r"(?:avg|mean|median)\s*[:=]\s*([\d.]+)\s*ms",
            r"([\d.]+)\s*ms[/\s]*iter",
            r"Time[:\s]*([\d.]+)\s*ms",
        ]:
            match = re.search(pattern, proc.stdout, re.IGNORECASE)
            if match:
                return float(match.group(1))

        # Strategy 3: Use wall-clock as last resort (very rough)
        if wall_ms > 100:  # only if the script took meaningful time
            return wall_ms
    except (subprocess.TimeoutExpired, Exception):
        pass

    return 0.0


def _measure_speedup(
    cfg: dict,
    task_dir: Path,
    baseline_path: str,
    optimized_path: str,
    num_runs: int = 5,
) -> float:
    """Measure speedup with multiple runs, outlier rejection, and variance check.

    Runs each script `num_runs` times, drops top/bottom 10%, and uses
    the median of the remaining samples.  Stores a ``_high_variance``
    warning in cfg if std > 20% of mean.
    """
    perf_cfg = cfg.get("performance", {})
    perf_cmd = perf_cfg.get("command", "")
    python_bin = perf_cmd.split()[0] if perf_cmd else "python3"

    def _robust_median(path: str) -> tuple[float, bool]:
        samples = []
        for _ in range(num_runs):
            ms = _run_benchmark_script(path, python_bin, str(task_dir))
            if ms > 0:
                samples.append(ms)
        if not samples:
            return 0.0, False

        samples.sort()
        n = len(samples)
        trim = max(1, n // 10)
        if n > 3:
            trimmed = samples[trim: n - trim]
        else:
            trimmed = samples

        median = trimmed[len(trimmed) // 2]
        high_var = False
        if len(trimmed) > 1:
            mean = sum(trimmed) / len(trimmed)
            if mean > 0:
                variance = sum((x - mean) ** 2 for x in trimmed) / len(trimmed)
                std = variance ** 0.5
                if std / mean > 0.20:
                    high_var = True
        return median, high_var

    baseline_ms, b_var = _robust_median(baseline_path)
    optimized_ms, o_var = _robust_median(optimized_path)

    if b_var or o_var:
        cfg["_high_variance"] = True
        print("    [grader] WARNING: high measurement variance (std > 20% of mean)",
              file=sys.stderr)

    if baseline_ms > 0 and optimized_ms > 0:
        ratio = baseline_ms / optimized_ms
        if ratio > 100:
            return 0.0
        return ratio
    return 0.0


def _apply_tampering_penalties(
    raw: dict,
    solution: Path,
    baseline_path: str,
    compiled: bool,
    correct: bool,
    speedup: float,
    speedup_cap: float = 0.0,
) -> tuple[bool, float]:
    """Detect benchmark tampering and apply correctness/speedup penalties.

    Args:
        speedup_cap: If > 0 and tampering is detected, cap speedup at this value
                     instead of the default 1.0x.  If 0, use default behaviour.

    Returns (adjusted_correct, adjusted_speedup).
    """
    tampering_warnings = _detect_benchmark_tampering(solution, baseline_path) if baseline_path else []
    if not tampering_warnings:
        return correct, speedup

    for tw in tampering_warnings:
        print(f"    [grader] TAMPERING DETECTED: {tw}", file=sys.stderr)
    raw["_tampering_warnings"] = tampering_warnings

    has_fake_pass = any("hardcoded PASS" in w for w in tampering_warnings)
    has_fake_benchmark = any("hardcoded BENCHMARK_MS" in w for w in tampering_warnings)

    if has_fake_pass:
        correct = False
        raw["_correctness_rejected_for_tampering"] = True
        print("    [grader] Marking correct=False: solution faked PASS output",
              file=sys.stderr)
    if has_fake_benchmark and speedup > 1.0:
        cap_val = speedup_cap if speedup_cap > 0 else 1.0
        print(f"    [grader] Capping speedup from {speedup:.2f}x to {cap_val:.2f}x: "
              f"fabricated benchmark number", file=sys.stderr)
        speedup = cap_val
        raw["_speedup_capped_for_tampering"] = True

    return correct, speedup


def _finalize_grading_result(
    task_id: str,
    raw: dict,
    cfg: dict,
    task_dir: Path,
    baseline_path: str,
    optimized_path: str,
    solution: Path,
    compare_timeout: int,
    speedup_cap: float = 0.0,
) -> KernelResult:
    """Shared post-processing: measure speedup, detect tampering, build KernelResult.

    Used by all three correctness modes (pytorch, library_test, accordo).
    If raw already contains a pre-computed speedup (via _magpie_speedup), that
    value is used instead of re-running _measure_speedup.
    """
    compiled = raw.get("compiled", False)
    correct = raw.get("correct", False)
    speedup = raw.pop("_magpie_speedup", 0.0)

    if compiled and correct and speedup <= 0:
        speedup = _measure_speedup(cfg, task_dir, baseline_path, optimized_path)
        if speedup <= 0:
            speedup = 1.0
            raw["_no_perf_data"] = True
            print("    [grader] No performance data; assuming 1.0x", file=sys.stderr)

    correct, speedup = _apply_tampering_penalties(
        raw, solution, baseline_path, compiled, correct, speedup,
        speedup_cap=speedup_cap,
    )

    return KernelResult(
        task_id=task_id,
        compiled=compiled,
        correct=correct,
        speedup=speedup,
        raw=raw,
        error=raw.get("error", ""),
    )


# ---------------------------------------------------------------------------
# Mode 2: Library test correctness
# ---------------------------------------------------------------------------

_TRUSTED_TEST_CMD_PREFIXES = (
    "python -m pytest",
    "pytest",
    "python -m unittest",
    "python -c",
)


def _run_library_test(
    unit_test_cmd: str,
    working_dir: str,
    solution_path: Path,
    timeout: int = 300,
) -> dict:
    """Run a library's own test suite to check correctness.

    Executes the unit_test_command (typically pytest) as a subprocess.
    The solution directory is prepended to PYTHONPATH so the library tests
    can import the optimized kernel.

    Only commands starting with known-safe prefixes are allowed to use
    shell=True.  Arbitrary shell commands from agent-generated configs
    are rejected.

    Returns a dict with 'compiled', 'correct', and diagnostic info.
    """
    result: dict = {"_correctness_mode": "library_test"}
    if not unit_test_cmd.strip():
        result["error"] = "empty unit_test_command"
        return result

    stripped = unit_test_cmd.strip()
    if not any(stripped.startswith(p) for p in _TRUSTED_TEST_CMD_PREFIXES):
        result["compiled"] = False
        result["correct"] = False
        result["error"] = (
            f"unit_test_command rejected: must start with one of "
            f"{_TRUSTED_TEST_CMD_PREFIXES}. Got: {stripped[:80]}"
        )
        print(f"    [grader] REJECTED untrusted test command: {stripped[:80]}", file=sys.stderr)
        return result

    env = os.environ.copy()
    existing = env.get("PYTHONPATH", "")
    sol_dir = str(solution_path.parent.resolve())
    env["PYTHONPATH"] = f"{sol_dir}:{existing}" if existing else sol_dir

    # Use shell mode for commands with shell constructs
    _shell_chars = ("|", "&&", "||", ";", "$", "`", ">", "<")
    use_shell = any(ch in unit_test_cmd for ch in _shell_chars)
    cmd: str | list[str] = unit_test_cmd if use_shell else shlex.split(unit_test_cmd)

    print(f"    [grader] library_test: {unit_test_cmd}", file=sys.stderr)
    print(f"    [grader] working_dir: {working_dir}", file=sys.stderr)

    try:
        proc = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=timeout,
            cwd=working_dir if working_dir else None,
            env=env,
            shell=use_shell,
        )

        result["exit_code"] = proc.returncode
        result["stdout"] = proc.stdout[-2000:] if len(proc.stdout) > 2000 else proc.stdout
        result["stderr"] = proc.stderr[-2000:] if len(proc.stderr) > 2000 else proc.stderr

        if proc.returncode == 0:
            result["compiled"] = True
            result["correct"] = True
            passed = re.search(r"(\d+)\s+passed", proc.stdout)
            if passed:
                result["tests_passed"] = int(passed.group(1))
            print(f"    [grader] library_test PASSED", file=sys.stderr)
        else:
            result["compiled"] = True
            result["correct"] = False
            failed = re.search(r"(\d+)\s+failed", proc.stdout)
            if failed:
                result["tests_failed"] = int(failed.group(1))
            error_match = re.search(r"(ERRORS?|FAILED)\s*.*", proc.stdout)
            result["error"] = error_match.group(0)[:200] if error_match else f"exit code {proc.returncode}"
            print(f"    [grader] library_test FAILED (exit {proc.returncode})", file=sys.stderr)

    except subprocess.TimeoutExpired:
        result["compiled"] = True
        result["correct"] = False
        result["error"] = f"library_test timed out ({timeout}s)"
        print(f"    [grader] library_test TIMEOUT ({timeout}s)", file=sys.stderr)
    except FileNotFoundError as e:
        result["compiled"] = False
        result["correct"] = False
        result["error"] = f"command not found: {e}"
        print(f"    [grader] library_test command not found: {e}", file=sys.stderr)

    return result


# ---------------------------------------------------------------------------
# Mode 3: Accordo HSA-level correctness
# ---------------------------------------------------------------------------

def _run_accordo_check(
    accordo_cfg: dict,
    working_dir: str,
    timeout: int = 300,
) -> dict:
    """Run Accordo HSA-level validation for HIP/C++ kernels.

    Invokes `accordo validate` CLI to compare GPU buffer outputs between
    reference and optimized binaries at the HSA runtime level.

    Returns a dict with 'compiled', 'correct', and diagnostic info.
    """
    result: dict = {"_correctness_mode": "accordo"}

    if not shutil.which("accordo"):
        result["compiled"] = False
        result["correct"] = False
        result["error"] = (
            "'accordo' CLI not found on PATH. Install IntelliKit Accordo "
            "(pip install intellikit[accordo])."
        )
        print(f"    [grader] accordo CLI not found", file=sys.stderr)
        return result

    kernel_name = accordo_cfg.get("kernel_name", "")
    ref_binary = accordo_cfg.get("reference_binary", "")
    opt_binary = accordo_cfg.get("optimized_binary", "")
    tolerance = accordo_cfg.get("tolerance", 0.001)
    _MAX_ACCORDO_TIMEOUT = 900  # 15 min hard cap
    acc_timeout = min(int(accordo_cfg.get("timeout_seconds", timeout)), _MAX_ACCORDO_TIMEOUT)
    acc_working_dir = accordo_cfg.get("working_directory", working_dir) or working_dir

    acc_working_dir = os.path.expandvars(acc_working_dir)

    if not kernel_name:
        result["error"] = "accordo config missing 'kernel_name'"
        return result
    if not ref_binary or not opt_binary:
        result["error"] = "accordo config missing 'reference_binary' or 'optimized_binary'"
        return result

    cmd = [
        "accordo", "validate",
        "--kernel-name", kernel_name,
        "--ref-binary", ref_binary,
        "--opt-binary", opt_binary,
        "--tolerance", str(tolerance),
        "--timeout", str(int(acc_timeout)),
        "--working-dir", acc_working_dir,
        "--log-level", "INFO",
    ]

    kernel_args = accordo_cfg.get("kernel_args")
    if kernel_args:
        if isinstance(kernel_args, list):
            args_str = ",".join(f"{name}:{typ}" for name, typ in kernel_args)
        else:
            args_str = str(kernel_args)
        cmd.extend(["--kernel-args", args_str])

    print(f"    [grader] accordo: {' '.join(cmd)}", file=sys.stderr)

    try:
        proc = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=int(acc_timeout) * 2 + 60,
            cwd=acc_working_dir,
        )

        result["exit_code"] = proc.returncode
        result["stdout"] = proc.stdout[-2000:] if len(proc.stdout) > 2000 else proc.stdout
        result["stderr"] = proc.stderr[-2000:] if len(proc.stderr) > 2000 else proc.stderr

        # Accordo outputs JSON on stdout (may have non-JSON prefix from binary)
        stdout_text = proc.stdout.strip()
        json_start = stdout_text.find("{")
        if json_start > 0:
            stdout_text = stdout_text[json_start:]
        try:
            output = json.loads(stdout_text)
            result["accordo_output"] = output
            is_valid = output.get("is_valid", output.get("valid", False))
            result["compiled"] = True
            result["correct"] = is_valid
            if is_valid:
                result["num_arrays_validated"] = output.get("num_arrays_validated", 0)
                print(f"    [grader] accordo PASSED ({result['num_arrays_validated']} arrays validated)",
                      file=sys.stderr)
            else:
                result["num_mismatches"] = output.get("num_mismatches", 0)
                result["error"] = f"accordo validation failed: {output.get('num_mismatches', '?')} mismatches"
                print(f"    [grader] accordo FAILED ({result['num_mismatches']} mismatches)",
                      file=sys.stderr)
        except (json.JSONDecodeError, ValueError):
            if proc.returncode == 0:
                result["compiled"] = True
                result["correct"] = True
                print(f"    [grader] accordo PASSED (non-JSON output)", file=sys.stderr)
            else:
                result["compiled"] = True
                result["correct"] = False
                result["error"] = f"accordo failed (exit {proc.returncode})"
                print(f"    [grader] accordo FAILED (exit {proc.returncode})", file=sys.stderr)

    except subprocess.TimeoutExpired:
        result["compiled"] = True
        result["correct"] = False
        result["error"] = f"accordo timed out ({acc_timeout}s)"
        print(f"    [grader] accordo TIMEOUT ({acc_timeout}s)", file=sys.stderr)
    except FileNotFoundError:
        # Shouldn't reach here — shutil.which guard above catches this.
        # Kept as safety net for race conditions (binary removed between check and exec).
        result["compiled"] = False
        result["correct"] = False
        result["error"] = "'accordo' CLI not found"
        print(f"    [grader] accordo CLI not found (race condition)", file=sys.stderr)

    return result


# ---------------------------------------------------------------------------
# Magpie performance measurement for non-pytorch modes
# ---------------------------------------------------------------------------

def _try_magpie_perf_measurement(
    raw: dict,
    baseline_path: str,
    optimized_path: str,
    task_dir: Path,
    compare_timeout: int,
    solution: Path,
    testcase_cmd: str | None = None,
) -> None:
    """Attempt Magpie compare for performance measurement only.

    Called after library_test or accordo has already determined correctness.
    If Magpie provides timing data, injects ``_magpie_speedup`` into *raw*
    so that ``_finalize_grading_result`` uses Magpie numbers instead of the
    less-precise script-level benchmark.  The domain-specific correctness
    verdict is never overridden.

    *testcase_cmd* tells Magpie how to invoke the kernel for benchmarking.
    Without it Magpie may skip the performance phase entirely.
    """
    if not baseline_path or not Path(baseline_path).exists():
        return
    if not optimized_path or not Path(optimized_path).exists():
        return

    kernel_type = _detect_kernel_type(solution)
    try:
        magpie_raw = run_magpie_compare(
            baseline_path=baseline_path,
            optimized_path=optimized_path,
            testcase_cmd=testcase_cmd,
            kernel_type=kernel_type,
            working_dir=str(task_dir.resolve()),
            timeout=compare_timeout,
        )
        if "error" not in magpie_raw:
            _, _, speedup = parse_compare_result(magpie_raw)
            if speedup > 0:
                raw["_magpie_speedup"] = speedup
                raw["_magpie_perf_source"] = "magpie_compare"
                print(f"    [grader] Magpie perf measurement: {speedup:.3f}x",
                      file=sys.stderr)
            else:
                print("    [grader] Magpie perf: no timing data returned",
                      file=sys.stderr)
        else:
            print(f"    [grader] Magpie perf skipped: {magpie_raw['error']}",
                  file=sys.stderr)
    except Exception as exc:
        print(f"    [grader] Magpie perf failed: {exc}", file=sys.stderr)


def grade_task(
    task_dir: Path,
    isolate_caches: bool = True,
    gpu_device: int = 0,
    trust_agent_config: bool = False,
    speedup_cap: float = 0.0,
    compute_rl_reward: bool = False,
    require_tags: bool = True,
    kernel_backend: str | None = None,
) -> KernelResult:
    """Grade a single task directory.

    Reads config.yaml, finds baseline + solution, runs Magpie compare.
    Falls back to script-level benchmarking when Magpie doesn't report timing.

    By default (trust_agent_config=False), any agent-authored config.yaml
    is validated and regenerated by the pipeline to prevent the agent from
    writing trivial tests or fabricating benchmark numbers.

    Parameters
    ----------
    compute_rl_reward : bool
        If True, also compute and attach the gated RL reward in
        ``result.raw["rl_reward"]``. Default False (legacy scoring only).
    require_tags : bool
        Whether ``<answer>`` tags are required for the gated reward.
    kernel_backend : str | None
        Override for the kernel backend (``"triton"`` or ``"hip"``).
        Auto-detected from solution file extension if None.
    """
    task_id  = task_dir.name
    solution = find_solution(task_dir)
    config   = task_dir / "config.yaml"

    if solution is None:
        return KernelResult(task_id=task_id, error="no solution file found")

    if not trust_agent_config and validate_config is not None:
        validation = validate_config(task_dir)
        for w in validation.warnings:
            print(f"    [config] {w}", file=sys.stderr)
        for e in validation.errors:
            print(f"    [config] ERROR: {e}", file=sys.stderr)
        if not validation.valid:
            if write_config is not None:
                try:
                    write_config(task_dir, gpu_device=gpu_device)
                    print(f"    [config] Regenerated trusted config.yaml", file=sys.stderr)
                except Exception as exc:
                    if not config.exists():
                        return KernelResult(
                            task_id=task_id,
                            error=f"Cannot generate config.yaml: {exc}",
                        )
    elif not config.exists():
        return KernelResult(
            task_id=task_id,
            compiled=True,
            error=f"config.yaml missing in {task_dir}; solution exists but cannot run Magpie without config",
        )

    clear_pycache(solution)

    if isolate_caches:
        with isolated_grading_env(gpu_device=gpu_device):
            result = _grade_task_inner(task_dir, task_id, solution, config, speedup_cap)
    else:
        result = _grade_task_inner(task_dir, task_id, solution, config, speedup_cap)

    if compute_rl_reward:
        _attach_gated_reward(result, task_dir, require_tags, kernel_backend)

    return result


def _attach_gated_reward(
    result: KernelResult,
    task_dir: Path,
    require_tags: bool,
    kernel_backend: str | None,
) -> None:
    """Compute and attach the RL gated reward to a KernelResult.

    Stores the reward in ``result.raw["rl_reward"]`` without affecting
    ``result.score`` (the legacy leaderboard score).
    """
    try:
        from score import compute_reward_gated
    except ImportError:
        result.raw["rl_reward"] = None
        return

    solution = find_solution(task_dir)
    if solution is None:
        result.raw["rl_reward"] = None
        return

    try:
        solution_str = solution.read_text(encoding="utf-8", errors="replace")
    except OSError:
        result.raw["rl_reward"] = None
        return

    # Determine backend from file extension if not provided
    if kernel_backend is None:
        kernel_backend = "hip" if solution.suffix in (".hip", ".cu") else "triton"

    # Extract timing from raw results
    raw = result.raw
    baseline_ms = float(raw.get("baseline_ms", 0) or 0)
    optimized_ms = float(raw.get("optimized_ms", 0) or 0)
    # Synthesize from speedup ratio when absolute times aren't available
    if baseline_ms <= 0 and optimized_ms <= 0 and result.speedup > 0:
        optimized_ms = 1.0
        baseline_ms = result.speedup * optimized_ms

    correctness_score = 1.0 if result.correct else 0.0
    hacking_detected = bool(raw.get("_gaming_warnings"))
    timed_out = "timed out" in (result.error or "").lower()

    magpie_result = {
        "compiled": result.compiled,
        "correctness_score": correctness_score,
        "baseline_ms": baseline_ms,
        "optimized_ms": optimized_ms,
        "hacking_detected": hacking_detected,
        "timed_out": timed_out,
    }

    # Build ground truth from config metadata
    ground_truth: dict = {}
    cfg_path = task_dir / "config.yaml"
    if cfg_path.exists():
        try:
            cfg = parse_task_config(cfg_path)
            meta = cfg.get("_pipeline_metadata", {})
            if meta.get("allowed_imports"):
                ground_truth["allowed_imports"] = meta["allowed_imports"]
            if meta.get("op_type"):
                ground_truth["op_type"] = meta["op_type"]
        except Exception:
            pass

    trace_context = {"task_id": result.task_id}

    # Compute gated reward using individual components directly.
    # The full compute_gated_reward() AST gate is designed for RL training
    # with self-contained kernels. Apex pipeline kernels are real library code
    # (wrappers importing from sub-modules), so we skip the AST gate and use
    # the existing _detect_benchmark_tampering for cheat detection instead.
    try:
        from reward_fn import (
            R_FORMAT_PASS, R_COMPILE_PASS, R_CORRECT_WEIGHT,
            compute_performance_reward,
        )
        r_format = R_FORMAT_PASS  # bare .py files always get format pass
        r_compile = R_COMPILE_PASS if result.compiled else 0.0
        r_correct = R_CORRECT_WEIGHT * correctness_score
        r_perf = compute_performance_reward(
            baseline_ms, optimized_ms, correctness_score,
        )
        # Apply tampering penalty from existing anti-cheat system
        r_ast = -2.0 if hacking_detected else 0.0
        reward = r_format + r_ast + r_compile + r_correct + r_perf
        result.raw["rl_reward"] = round(reward, 4)
        result.raw["rl_reward_breakdown"] = {
            "r_format": r_format, "r_ast": r_ast,
            "r_compile": r_compile, "r_correct": round(r_correct, 4),
            "r_perf": round(r_perf, 4),
        }
    except Exception as exc:
        print(f"    [grader] gated reward failed: {exc}", file=sys.stderr)
        result.raw["rl_reward"] = None


def _grade_task_inner(
    task_dir: Path,
    task_id: str,
    solution: Path,
    config: Path,
    speedup_cap: float = 0.0,
) -> KernelResult:
    """Core grading logic (runs inside or outside cache isolation).

    Dispatches to the appropriate correctness mode based on config.yaml:
      - pytorch (default): magpie compare with testcase_cmd
      - library_test: run library's own test suite
      - accordo: HSA-level binary comparison via Accordo CLI
    """
    cfg = _parse_config(config)

    baseline_path = cfg.get("baseline", {}).get("path", "")

    corr_cfg = cfg.get("correctness", {})
    corr_mode = corr_cfg.get("mode", "pytorch")

    meta = cfg.get("_pipeline_metadata", {})
    framework = meta.get("framework", "")
    has_heavy_imports = framework in ("vllm", "sglang")
    compare_timeout = 600 if has_heavy_imports else 300

    # Resolve baseline path (shared across all modes that need it)
    if baseline_path:
        if not Path(baseline_path).is_absolute():
            baseline_path = str((task_dir / baseline_path).resolve())

        if not Path(baseline_path).exists():
            for fallback_name in ("baseline_ref.py", "baseline.py", "baseline_ref.hip", "baseline.hip"):
                fallback = task_dir / fallback_name
                if fallback.exists():
                    baseline_path = str(fallback.resolve())
                    print(f"    [grader] Configured baseline missing, using {fallback_name}", file=sys.stderr)
                    break
            else:
                rocm_root = REPO_ROOT / "tools" / "rocm"
                raw_bp = cfg.get("baseline", {}).get("path", "")
                for prefix in ("", "vllm/", "aiter/"):
                    candidate = rocm_root / prefix / raw_bp
                    if candidate.exists():
                        baseline_path = str(candidate.resolve())
                        print(f"    [grader] Resolved baseline via tools/rocm/{prefix}", file=sys.stderr)
                        break

    optimized_path = cfg.get("optimized", {}).get("path", str(solution))
    if not Path(optimized_path).is_absolute():
        optimized_path = str((task_dir / optimized_path).resolve())

    # Testcase command for Magpie perf (correctness or performance section)
    magpie_testcase_cmd = (
        corr_cfg.get("command")
        or cfg.get("performance", {}).get("command")
        or None
    )

    # ── Mode 2: Library test ─────────────────────────────────────────────
    if corr_mode == "library_test":
        unit_test_cmd = corr_cfg.get("unit_test_command", "")
        lib_working_dir = corr_cfg.get("working_directory", str(task_dir.resolve()))

        if not unit_test_cmd:
            return KernelResult(
                task_id=task_id,
                error="library_test mode but no unit_test_command in config",
            )

        # Fallback: if working directory doesn't exist, switch to pytorch mode
        if lib_working_dir and not Path(lib_working_dir).is_dir():
            print(f"    [grader] library_test working_dir missing: {lib_working_dir}; "
                  f"falling back to pytorch mode", file=sys.stderr)
            corr_mode = "pytorch"
            # Fall through to pytorch mode below

    if corr_mode == "library_test":
        raw = _run_library_test(
            unit_test_cmd=unit_test_cmd,
            working_dir=lib_working_dir,
            solution_path=solution,
            timeout=compare_timeout,
        )

        if raw.get("correct") and baseline_path:
            _try_magpie_perf_measurement(
                raw, baseline_path, optimized_path,
                task_dir, compare_timeout, solution,
                testcase_cmd=magpie_testcase_cmd,
            )

        return _finalize_grading_result(
            task_id, raw, cfg, task_dir,
            baseline_path, optimized_path, solution, compare_timeout,
            speedup_cap=speedup_cap,
        )

    # ── Mode 3: Accordo HSA-level ────────────────────────────────────────
    if corr_mode == "accordo":
        accordo_inner = corr_cfg.get("accordo", {})
        acc_working_dir = corr_cfg.get("working_directory", str(task_dir.resolve()))

        raw = _run_accordo_check(
            accordo_cfg=accordo_inner,
            working_dir=acc_working_dir,
            timeout=compare_timeout,
        )

        if raw.get("correct") and baseline_path:
            _try_magpie_perf_measurement(
                raw, baseline_path, optimized_path,
                task_dir, compare_timeout, solution,
                testcase_cmd=magpie_testcase_cmd,
            )

        return _finalize_grading_result(
            task_id, raw, cfg, task_dir,
            baseline_path, optimized_path, solution, compare_timeout,
            speedup_cap=speedup_cap,
        )

    # ── Mode 1: PyTorch / Magpie compare (default) ───────────────────────
    if not baseline_path:
        # No baseline available — try compile-only check on the solution
        print("    [grader] No baseline path; attempting compile-only check", file=sys.stderr)
        python_bin = cfg.get("performance", {}).get("command", "python3").split()[0]
        # Resolve the actual solution file (config may say .hip but file is .py)
        sol_file = str(solution.resolve())
        compile_script = (
            f"import importlib.util; "
            f"s=importlib.util.spec_from_file_location('sol','{sol_file}'); "
            f"m=importlib.util.module_from_spec(s); s.loader.exec_module(m); print('OK')"
        )
        try:
            r = subprocess.run(
                [python_bin, "-c", compile_script],
                capture_output=True, text=True, timeout=60,
                cwd=str(task_dir),
            )
            compiled = r.returncode == 0 and "OK" in r.stdout
            if not compiled:
                print(f"    [grader] compile check: rc={r.returncode} stdout={r.stdout[:200]} stderr={r.stderr[:200]}", file=sys.stderr)
        except Exception as e:
            compiled = False
            print(f"    [grader] compile check exception: {e}", file=sys.stderr)

        speedup = 0.0
        if compiled:
            o_ms = _run_benchmark_script(sol_file, python_bin, str(task_dir))
            if o_ms > 0:
                speedup = 1.0  # no baseline to compare
                print(f"    [grader] Solution self-benchmark: {o_ms:.4f} ms", file=sys.stderr)

        return KernelResult(
            task_id=task_id,
            compiled=compiled,
            correct=compiled,  # assume correct if compiles (no baseline to compare)
            speedup=speedup,
            raw={"_no_baseline": True, "_compile_only": True},
            error="" if compiled else "solution failed to compile",
        )

    # Verify pipeline-generated correctness files haven't been tampered with
    protected_hashes = meta.get("protected_file_hashes", {})
    for fname, expected_hash in protected_hashes.items():
        fpath = task_dir / fname
        if not fpath.exists():
            return KernelResult(
                task_id=task_id,
                error=f"tamper check: pipeline file {fname} was deleted by agent",
            )
        actual_hash = hashlib.sha256(fpath.read_bytes()).hexdigest()
        if actual_hash != expected_hash:
            print(f"    [grader] TAMPER DETECTED: {fname} was modified by agent", file=sys.stderr)
            return KernelResult(
                task_id=task_id,
                error=f"tamper check: {fname} was modified (expected {expected_hash[:12]}..., got {actual_hash[:12]}...)",
            )

    testcase_cmd = corr_cfg.get("command")
    kernel_type = _detect_kernel_type(solution)

    raw = run_magpie_compare(
        baseline_path=baseline_path,
        optimized_path=optimized_path,
        testcase_cmd=testcase_cmd,
        kernel_type=kernel_type,
        working_dir=str(task_dir.resolve()),
        timeout=compare_timeout,
    )

    if "error" in raw:
        return KernelResult(task_id=task_id, raw=raw, error=raw["error"])

    compiled, correct, speedup = parse_compare_result(raw)

    # Magpie may not report timing; fall back to script-level benchmarking
    if compiled and correct and speedup <= 0:
        perf_cfg = cfg.get("performance", {})
        perf_cmd = perf_cfg.get("command", "")
        python_bin = perf_cmd.split()[0] if perf_cmd else "python3"

        b_ms = _run_benchmark_script(baseline_path, python_bin, str(task_dir))
        o_ms = _run_benchmark_script(optimized_path, python_bin, str(task_dir))
        if b_ms > 0 and o_ms > 0:
            speedup = b_ms / o_ms
            if speedup > 100:
                speedup = 0.0
            raw["baseline_ms"] = round(b_ms, 4)
            raw["optimized_ms"] = round(o_ms, 4)
            raw["_benchmark_speedup"] = round(speedup, 4)

    # Store Magpie results into raw so _finalize_grading_result can use them
    raw["compiled"] = compiled
    raw["correct"] = correct
    if speedup > 0:
        raw["_magpie_speedup"] = speedup

    return _finalize_grading_result(
        task_id, raw, cfg, task_dir,
        baseline_path, optimized_path, solution, compare_timeout,
        speedup_cap=speedup_cap,
    )


def grade_all(
    output_dir: Path,
    task_filter: str | None = None,
    isolate_caches: bool = True,
    gpu_device: int = 0,
    trust_agent_config: bool = False,
) -> list[KernelResult]:
    if not output_dir.exists():
        print(f"[kernel_grader] output dir not found: {output_dir}", file=sys.stderr)
        return []

    tasks = find_tasks(output_dir)
    if task_filter:
        tasks = [t for t in tasks if task_filter in t.name]

    if not tasks:
        print(f"[kernel_grader] no tasks found in {output_dir}", file=sys.stderr)
        return []

    results = []
    for task_dir in tasks:
        print(f"  grading {task_dir.name} ...", file=sys.stderr)
        r = grade_task(
            task_dir,
            isolate_caches=isolate_caches,
            gpu_device=gpu_device,
            trust_agent_config=trust_agent_config,
        )
        results.append(r)
        status = "✓" if r.correct else ("?" if r.compiled else "✗")
        print(
            f"    [{status}] compiled={r.compiled} correct={r.correct} "
            f"speedup={r.speedup:.2f}× score={r.score:.0f}",
            file=sys.stderr,
        )

    return results


def summarise(results: list[KernelResult]) -> dict:
    if not results:
        return {"total_score": 0, "tasks": 0, "results": []}

    total     = sum(r.score    for r in results)
    compiled  = sum(r.compiled for r in results)
    correct   = sum(r.correct  for r in results)
    avg_sp    = sum(r.speedup  for r in results if r.correct) / max(1, correct)

    return {
        "total_score":   round(total, 2),
        "tasks":         len(results),
        "compiled":      compiled,
        "correct":       correct,
        "avg_speedup":   round(avg_sp, 4),
        "scoring_notes": {
            "compiled":  f"+{PTS_COMPILED} pts",
            "correct":   f"+{PTS_CORRECT} pts",
            "speedup":   "+speedup×100 pts",
        },
        "results": [r.to_dict() for r in results],
    }


def main():
    parser = argparse.ArgumentParser(
        description="Kernel-level grader — scores optimized kernels via Magpie."
    )
    parser.add_argument(
        "--output-dir", default=str(OUTPUT_DIR),
        help=f"Path to the output/ directory (default: {OUTPUT_DIR})",
    )
    parser.add_argument(
        "--task", default=None,
        help="Grade only tasks whose ID contains this string.",
    )
    parser.add_argument(
        "--json", action="store_true",
        help="Print full JSON summary to stdout.",
    )
    args = parser.parse_args()

    output_dir = Path(args.output_dir)
    print(f"[kernel_grader] scanning {output_dir}", file=sys.stderr)

    results = grade_all(output_dir, task_filter=args.task)
    summary = summarise(results)

    if args.json:
        print(json.dumps(summary, indent=2))
    else:
        print(f"\n{'='*50}")
        print(f"  Kernel grader results")
        print(f"{'='*50}")
        print(f"  Tasks:        {summary['tasks']}")
        print(f"  Compiled:     {summary['compiled']} / {summary['tasks']}")
        print(f"  Correct:      {summary['correct']} / {summary['tasks']}")
        print(f"  Avg speedup:  {summary['avg_speedup']:.3f}×")
        print(f"  TOTAL SCORE:  {summary['total_score']:.1f} pts")
        print(f"{'='*50}")
        for r in results:
            d = r.to_dict()
            flag = "PASS" if d["correct"] else ("COMPILE" if d["compiled"] else "FAIL")
            print(f"  {flag:7s}  {d['task_id']:30s}  "
                  f"{d['speedup']:.2f}×  {d['score']:.0f} pts"
                  + (f"  [{d['error']}]" if d["error"] else ""))


if __name__ == "__main__":
    main()
